services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    expose:
      - "8080"
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imagetransformation.rule=Host(`imagetransformation.ru`)"
      - "traefik.http.routers.imagetransformation.entrypoints=websecure"
      - "traefik.http.routers.imagetransformation.tls=true"
      - "traefik.http.routers.imagetransformation.tls.certresolver=mytlschallenge"
      - "traefik.http.services.imagetransformation.loadbalancer.server.port=8080"

networks:
  n8n_default:
    external: true
