services:
  postgre_imagetransformer:
    image: postgres:16-alpine
    container_name: postgre_imagetransformer
    restart: unless-stopped
    environment:
      POSTGRES_DB: imagetransformer
      POSTGRES_USER: imagetransformer
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_default

  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    expose:
      - "8080"
    depends_on:
      - postgre_imagetransformer
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imagetransformation.rule=Host(`imagetransformation.ru`)"
      - "traefik.http.routers.imagetransformation.entrypoints=websecure"
      - "traefik.http.routers.imagetransformation.tls=true"
      - "traefik.http.routers.imagetransformation.tls.certresolver=mytlschallenge"
      - "traefik.http.services.imagetransformation.loadbalancer.server.port=8080"

volumes:
  postgres_data:

networks:
  n8n_default:
    external: true
